[project]
name = "dittmann-maug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markitdown[all]>=0.1.4",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
]
